Update patch set 2
Patch Set 2:

for some reason tox is looking for the permissions files (which is not included in your review) resulting a failure on the api.

  File "/home/jenkins/workspace/dci-tox/dci-control-server/dci/api/v1/permissions.py", line 39, in <module>
    @auth.login_required
AttributeError: 'module' object has no attribute 'login_required'

This cause an infinite loop in the start_api.sh script. This problem will be fix in 8760.

I will rebase your patch to include the permission code.

Patch-set: 2
Reviewer: Gerrit User 56 <56@6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0>
Label: Code-Review=0