Elasticsearch: Update methode call parameters
The signature of the upstream function[1] does not match the one here.

Hence whenever we are doing a POST request it fails with :

> TypeError: search() got an unexpected keyword argument 'request_cache'

[1]
https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/__init__.py#L461

Change-Id: I872823464cbd220710b672bab2dc4db72c7d5613