client: do not print log on STDOUT anymore
This was generatic various error like this on with Py27:
    UnicodeEncodeError: 'ascii' codec can't encode character
This error is common and well document. We need to spend more time to
understand what's going on. For the moment, the priority is to get
Khaleesi project integrated. So let's simplify the problem by dropping
these lines.

Change-Id: I5e34289d3432210f31bafc61272e7708643788d7